logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
  port: # 로컬용 포트 번호
    8081
#  port: # 배포용 포트 번호 (Nginx)
#    5000
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-exxa7rnbas-stack-awsebrdsdatabase-83nh5tgicvgk.c9pavs7woqch.ap-northeast-2.rds.amazonaws.com:3306/cdsproject
    username: root
    password: rlaxogjs8312
  sql.init.mode: always
cloud:
  aws:
    s3:
      bucket: cds-project-bucket
    credentials:
      access-key: AKIAWCBPU4AM3TRM5MW4
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false