logging:
  level:
    org.apache.coyote.http11:
      debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
  port: 8080
  second:
    port: 8081
  third:
    port: 8080
file:
  dir:
    C:\Users\tae77\OneDrive\cds_project_upload\
